#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os, re
Import('env')

Import('mu2e_helper')

helper=mu2e_helper(env)

rootlibs  = env['ROOTLIBS']

mainlib = helper.make_mainlib ( [
    "openblas"
] )

helper.make_plugins( [
  mainlib,
  "openblas",
  'art_Framework_Core',
  'art_Framework_Principal',
  'art_Framework_Services_Registry',
  'art_root_io_tfile_support',
  'art_root_io_TFileService',
  'art_Framework_Services_Optional_RandomNumberGenerator_service',
  'art_Framework_Services_System_TriggerNamesService_service',
  'art_Persistency_Common',
  'art_Persistency_Provenance',
  'art_Utilities',
  'canvas',
  'MF_MessageLogger',
  'fhiclcpp',
  'fhiclcpp_types',
  'tbb',
  'cetlib',
  'cetlib_except',
  rootlibs,
  'xerces-c',
  'boost_filesystem',
  'hep_concurrency',
'pthread'
] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
